In [126]:
import pandas as pd
import numpy as np

In [127]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample_submission = pd.read_csv('sample_submission.csv')

## train

In [128]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [129]:
train[train.duplicated()]

Empty DataFrame
Columns: [PassengerId, HomePlanet, CryoSleep, Cabin, Destination, Age, VIP, RoomService, FoodCourt, ShoppingMall, Spa, VRDeck, Name, Transported]
Index: []

In [130]:
test[test.duplicated()]

Empty DataFrame
Columns: [PassengerId, HomePlanet, CryoSleep, Cabin, Destination, Age, VIP, RoomService, FoodCourt, ShoppingMall, Spa, VRDeck, Name]
Index: []

In [131]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

---

### Homeplanet

In [132]:
train['Group'] = train['PassengerId'].str[:4]

In [133]:
home_group = train.groupby(['Group', 'HomePlanet']).size().reset_index()

In [134]:
home_group.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6107 entries, 0 to 6106
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Group       6107 non-null   object
 1   HomePlanet  6107 non-null   object
 2   0           6107 non-null   int64
dtypes: int64(1), object(2)
memory usage: 143.3+ KB

In [135]:
train[train['HomePlanet'].isnull()]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Group
59,0064_02,NaN,True,E/3/S,TRAPPIST-1e,33.0,False,0.0,0.0,NaN,0.0,0.0,Colatz Keen,True,0064
113,0119_01,NaN,False,A/0/P,TRAPPIST-1e,39.0,False,0.0,2344.0,0.0,65.0,6898.0,Batan Coning,False,0119
186,0210_01,NaN,True,D/6/P,55 Cancri e,24.0,False,0.0,0.0,NaN,0.0,0.0,Arraid Inicont,True,0210
225,0242_01,NaN,False,F/46/S,TRAPPIST-1e,18.0,False,313.0,1.0,691.0,283.0,0.0,Almone Sté,False,0242
234,0251_01,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True,0251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8515,9084_01,NaN,False,E/582/P,TRAPPIST-1e,25.0,False,1258.0,0.0,22.0,19.0,0.0,Jurs Mone,False,9084
8613,9194_01,NaN,False,E/603/S,55 Cancri e,53.0,False,0.0,4017.0,0.0,13.0,3147.0,NaN,False,9194
8666,9248_01,NaN,False,F/1792/S,55 Cancri e,38.0,NaN,28.0,1208.0,973.0,207.0,0.0,Gian Perle,True,9248
8674,9257_01,NaN,False,F/1892/P,TRAPPIST-1e,13.0,False,39.0,0.0,1085.0,24.0,0.0,Ties Apple,False,9257
8684,9274_01,NaN,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True,9274

In [136]:
home_dict = {}
for k,v in zip(home_group['Group'], home_group['HomePlanet']):
    home_dict[k] = v

In [137]:
home_dict

{'0001': 'Europa',
 '0002': 'Earth',
 '0003': 'Europa',
 '0004': 'Earth',
 '0005': 'Earth',
 '0006': 'Earth',
 '0007': 'Earth',
 '0008': 'Europa',
 '0009': 'Mars',
 '0010': 'Earth',
 '0011': 'Earth',
 '0012': 'Earth',
 '0014': 'Mars',
 '0015': 'Earth',
 '0016': 'Mars',
 '0017': 'Earth',
 '0020': 'Earth',
 '0022': 'Mars',
 '0024': 'Europa',
 '0025': 'Earth',
 '0026': 'Europa',
 '0028': 'Mars',
 '0030': 'Earth',
 '0031': 'Mars',
 '0034': 'Europa',
 '0035': 'Mars',
 '0036': 'Earth',
 '0038': 'Earth',
 '0039': 'Earth',
 '0041': 'Earth',
 '0043': 'Europa',
 '0044': 'Earth',
 '0045': 'Mars',
 '0050': 'Earth',
 '0051': 'Earth',
 '0052': 'Earth',
 '0053': 'Earth',
 '0056': 'Europa',
 '0058': 'Earth',
 '0061': 'Earth',
 '0062': 'Earth',
 '0064': 'Mars',
 '0066': 'Earth',
 '0067': 'Earth',
 '0068': 'Mars',
 '0069': 'Earth',
 '0070': 'Earth',
 '0071': 'Earth',
 '0072': 'Earth',
 '0073': 'Mars',
 '0074': 'Europa',
 '0076': 'Mars',
 '0077': 'Mars',
 '0078': 'Europa',
 '0081': 'Earth',
 '0082': 'Mars',
 '0084': 'Earth',
 '0085': 'Europa',
 '0086': 'Earth',
 '0088': 'Mars',
 '0090': 'Earth',
 '0091': 'Earth',
 '0092': 'Earth',
 '0097': 'Europa',
 '0098': 'Earth',
 '0099': 'Earth',
 '0101': 'Mars',
 '0102': 'Earth',
 '0103': 'Earth',
 '0105': 'Earth',
 '0107': 'Mars',
 '0108': 'Earth',
 '0110': 'Europa',
 '0111': 'Europa',
 '0112': 'Europa',
 '0113': 'Earth',
 '0114': 'Earth',
 '0115': 'Mars',
 '0116': 'Europa',
 '0119': 'Europa',
 '0120': 'Mars',
 '0122': 'Earth',
 '0123': 'Earth',
 '0126': 'Mars',
 '0127': 'Mars',
 '0128': 'Mars',
 '0129': 'Earth',
 '0133': 'Mars',
 '0134': 'Earth',
 '0136': 'Earth',
 '0138': 'Earth',
 '0139': 'Europa',
 '0140': 'Earth',
 '0141': 'Mars',
 '0144': 'Earth',
 '0146': 'Earth',
 '0147': 'Earth',
 '0148': 'Mars',
 '0149': 'Earth',
 '0151': 'Earth',
 '0152': 'Earth',
 '0160': 'Earth',
 '0163': 'Europa',
 '0164': 'Earth',
 '0165': 'Mars',
 '0167': 'Mars',
 '0169': 'Earth',
 '0170': 'Earth',
 '0171': 'Earth',
 '0172': 'Earth',
 '0173': 'Earth',
 '0174': 'Earth',
 '0177': 'Europa',
 '0178': 'Mars',
 '0179': 'Earth',
 '0181': 'Earth',
 '0182': 'Europa',
 '0183': 'Earth',
 '0186': 'Earth',
 '0188': 'Earth',
 '0189': 'Earth',
 '0190': 'Earth',
 '0192': 'Earth',
 '0193': 'Mars',
 '0195': 'Mars',
 '0196': 'Mars',
 '0197': 'Europa',
 '0198': 'Earth',
 '0199': 'Earth',
 '0200': 'Earth',
 '0201': 'Europa',
 '0202': 'Europa',
 '0203': 'Europa',
 '0205': 'Earth',
 '0206': 'Europa',
 '0207': 'Earth',
 '0211': 'Mars',
 '0212': 'Earth',
 '0213': 'Earth',
 '0216': 'Earth',
 '0217': 'Earth',
 '0219': 'Earth',
 '0220': 'Earth',
 '0221': 'Mars',
 '0222': 'Mars',
 '0223': 'Earth',
 '0224': 'Mars',
 '0225': 'Earth',
 '0229': 'Earth',
 '0231': 'Mars',
 '0232': 'Earth',
 '0233': 'Mars',
 '0234': 'Earth',
 '0237': 'Europa',
 '0239': 'Mars',
 '0240': 'Mars',
 '0241': 'Europa',
 '0243': 'Earth',
 '0244': 'Mars',
 '0245': 'Europa',
 '0246': 'Mars',
 '0248': 'Europa',
 '0250': 'Earth',
 '0252': 'Earth',
 '0253': 'Earth',
 '0254': 'Earth',
 '0255': 'Europa',
 '0257': 'Mars',
 '0258': 'Earth',
 '0260': 'Europa',
 '0261': 'Earth',
 '0263': 'Earth',
 '0265': 'Europa',
 '0267': 'Earth',
 '0269': 'Earth',
 '0270': 'Earth',
 '0275': 'Europa',
 '0277': 'Earth',
 '0278': 'Earth',
 '0281': 'Earth',
 '0282': 'Earth',
 '0283': 'Earth',
 '0285': 'Europa',
 '0286': 'Earth',
 '0287': 'Europa',
 '0288': 'Earth',
 '0289': 'Europa',
 '0290': 'Europa',
 '0291': 'Europa',
 '0294': 'Europa',
 '0297': 'Earth',
 '0298': 'Europa',
 '0301': 'Earth',
 '0302': 'Earth',
 '0304': 'Europa',
 '0305': 'Europa',
 '0306': 'Earth',
 '0307': 'Earth',
 '0309': 'Earth',
 '0310': 'Europa',
 '0313': 'Earth',
 '0314': 'Earth',
 '0316': 'Europa',
 '0320': 'Earth',
 '0322': 'Earth',
 '0324': 'Earth',
 '0326': 'Earth',
 '0327': 'Earth',
 '0330': 'Europa',
 '0331': 'Earth',
 '0333': 'Mars',
 '0334': 'Mars',
 '0336': 'Earth',
 '0337': 'Mars',
 '0338': 'Earth',
 '0340': 'Europa',
 '0341': 'Earth',
 '0343': 'Earth',
 '0345': 'Mars',
 '0346': 'Earth',
 '0347': 'Mars',
 '0348': 'Mars',
 '0350': 'Earth',
 '0352': 'Mars',
 '0355': 'Earth',
 '0356': 'Europa',
 '0357': 'Earth',
 '0358': 'Earth',
 '0359': 'Earth',
 '0360': 'Earth',
 '0361': 'Earth',
 '0365': 'Earth',
 '0368': 'Mars',
 '0369': 'Earth',
 '0370': 'Earth',
 '0371': 'Mars',
 '0372': 'Earth',
 '0373': 'Earth',
 '0375': 'Earth',
 '0376': 'Earth',
 '0377': 'Europa',
 '0378': 'Europa',
 '0379': 'Earth',
 '0380': 'Europa',
 '0381': 'Europa',
 '0383': 'Earth',
 '0384': 'Earth',
 '0385': 'Earth',
 '0387': 'Earth',
 '0388': 'Earth',
 '0389': 'Earth',
 '0391': 'Europa',
 '0392': 'Earth',
 '0395': 'Europa',
 '0396': 'Earth',
 '0397': 'Mars',
 '0398': 'Mars',
 '0401': 'Mars',
 '0403': 'Mars',
 '0405': 'Earth',
 '0407': 'Earth',
 '0408': 'Mars',
 '0409': 'Mars',
 '0410': 'Earth',
 '0411': 'Earth',
 '0412': 'Europa',
 '0413': 'Earth',
 '0415': 'Earth',
 '0417': 'Europa',
 '0423': 'Europa',
 '0425': 'Mars',
 '0427': 'Europa',
 '0428': 'Europa',
 '0429': 'Europa',
 '0430': 'Earth',
 '0431': 'Mars',
 '0432': 'Mars',
 '0433': 'Europa',
 '0434': 'Mars',
 '0435': 'Earth',
 '0436': 'Earth',
 '0437': 'Earth',
 '0438': 'Europa',
 '0439': 'Europa',
 '0441': 'Earth',
 '0442': 'Earth',
 '0444': 'Mars',
 '0445': 'Earth',
 '0446': 'Europa',
 '0447': 'Earth',
 '0448': 'Earth',
 '0449': 'Earth',
 '0452': 'Mars',
 '0453': 'Europa',
 '0454': 'Europa',
 '0456': 'Earth',
 '0457': 'Earth',
 '0458': 'Europa',
 '0459': 'Earth',
 '0460': 'Earth',
 '0461': 'Earth',
 '0462': 'Earth',
 '0463': 'Mars',
 '0465': 'Earth',
 '0466': 'Earth',
 '0468': 'Earth',
 '0470': 'Mars',
 '0471': 'Europa',
 '0472': 'Earth',
 '0474': 'Earth',
 '0475': 'Earth',
 '0476': 'Mars',
 '0477': 'Earth',
 '0480': 'Earth',
 '0481': 'Earth',
 '0482': 'Earth',
 '0485': 'Europa',
 '0487': 'Europa',
 '0488': 'Earth',
 '0490': 'Earth',
 '0498': 'Europa',
 '0499': 'Mars',
 '0500': 'Mars',
 '0501': 'Europa',
 '0502': 'Mars',
 '0503': 'Mars',
 '0504': 'Europa',
 '0506': 'Mars',
 '0507': 'Earth',
 '0510': 'Europa',
 '0512': 'Europa',
 '0513': 'Earth',
 '0515': 'Europa',
 '0516': 'Europa',
 '0517': 'Earth',
 '0519': 'Earth',
 '0520': 'Earth',
 '0521': 'Earth',
 '0522': 'Earth',
 '0523': 'Earth',
 '0525': 'Earth',
 '0527': 'Mars',
 '0528': 'Europa',
 '0529': 'Earth',
 '0531': 'Earth',
 '0533': 'Mars',
 '0534': 'Europa',
 '0537': 'Earth',
 '0538': 'Earth',
 '0539': 'Europa',
 '0540': 'Mars',
 '0542': 'Earth',
 '0545': 'Earth',
 '0546': 'Earth',
 '0547': 'Earth',
 '0548': 'Earth',
 '0549': 'Mars',
 '0550': 'Earth',
 '0551': 'Earth',
 '0552': 'Europa',
 '0553': 'Europa',
 '0555': 'Europa',
 '0556': 'Earth',
 '0559': 'Earth',
 '0560': 'Earth',
 '0561': 'Earth',
 '0563': 'Mars',
 '0564': 'Europa',
 '0565': 'Mars',
 '0566': 'Mars',
 '0567': 'Earth',
 '0568': 'Europa',
 '0569': 'Earth',
 '0570': 'Europa',
 '0571': 'Europa',
 '0572': 'Earth',
 '0573': 'Earth',
 '0575': 'Europa',
 '0576': 'Earth',
 '0577': 'Earth',
 '0579': 'Earth',
 '0580': 'Earth',
 '0581': 'Earth',
 '0582': 'Mars',
 '0583': 'Mars',
 '0585': 'Mars',
 '0586': 'Europa',
 '0587': 'Mars',
 '0588': 'Earth',
 '0589': 'Earth',
 '0590': 'Earth',
 '0591': 'Earth',
 '0593': 'Mars',
 '0594': 'Earth',
 '0596': 'Mars',
 '0597': 'Earth',
 '0598': 'Earth',
 '0599': 'Mars',
 '0600': 'Europa',
 '0602': 'Mars',
 '0603': 'Earth',
 '0607': 'Europa',
 '0608': 'Earth',
 '0609': 'Mars',
 '0610': 'Earth',
 '0611': 'Earth',
 '0612': 'Europa',
 '0614': 'Earth',
 '0615': 'Earth',
 '0618': 'Earth',
 '0619': 'Europa',
 '0623': 'Earth',
 '0628': 'Earth',
 '0629': 'Earth',
 '0630': 'Mars',
 '0631': 'Mars',
 '0633': 'Mars',
 '0634': 'Earth',
 '0635': 'Earth',
 '0636': 'Earth',
 '0637': 'Mars',
 '0638': 'Europa',
 '0639': 'Earth',
 '0641': 'Earth',
 '0642': 'Europa',
 '0643': 'Mars',
 '0644': 'Europa',
 '0645': 'Earth',
 '0646': 'Europa',
 '0647': 'Mars',
 '0650': 'Earth',
 '0653': 'Mars',
 '0655': 'Mars',
 '0656': 'Earth',
 '0657': 'Earth',
 '0658': 'Earth',
 '0659': 'Earth',
 '0660': 'Earth',
 '0661': 'Europa',
 '0663': 'Earth',
 '0664': 'Europa',
 '0665': 'Mars',
 '0668': 'Earth',
 '0669': 'Earth',
 '0671': 'Earth',
 '0672': 'Earth',
 '0674': 'Earth',
 '0677': 'Earth',
 '0678': 'Earth',
 '0679': 'Earth',
 '0680': 'Earth',
 '0682': 'Mars',
 '0683': 'Mars',
 '0684': 'Mars',
 '0685': 'Earth',
 '0686': 'Mars',
 '0687': 'Mars',
 '0688': 'Mars',
 '0689': 'Europa',
 '0690': 'Mars',
 '0691': 'Mars',
 '0693': 'Europa',
 '0696': 'Earth',
 '0697': 'Earth',
 '0699': 'Mars',
 '0701': 'Europa',
 '0702': 'Earth',
 '0703': 'Earth',
 '0704': 'Earth',
 '0705': 'Earth',
 '0707': 'Earth',
 '0709': 'Europa',
 '0710': 'Mars',
 '0712': 'Mars',
 '0713': 'Earth',
 '0714': 'Earth',
 '0715': 'Europa',
 '0718': 'Earth',
 '0719': 'Mars',
 '0724': 'Earth',
 '0726': 'Earth',
 '0727': 'Earth',
 '0728': 'Earth',
 '0729': 'Earth',
 '0732': 'Earth',
 '0733': 'Earth',
 '0734': 'Earth',
 '0736': 'Earth',
 '0737': 'Europa',
 '0738': 'Mars',
 '0740': 'Europa',
 '0743': 'Earth',
 '0746': 'Earth',
 '0750': 'Earth',
 '0753': 'Europa',
 '0754': 'Europa',
 '0756': 'Europa',
 '0757': 'Mars',
 '0761': 'Europa',
 '0762': 'Earth',
 '0764': 'Earth',
 '0765': 'Mars',
 '0767': 'Earth',
 '0768': 'Europa',
 '0769': 'Europa',
 '0770': 'Earth',
 '0771': 'Earth',
 '0772': 'Europa',
 '0773': 'Earth',
 '0776': 'Earth',
 '0777': 'Europa',
 '0779': 'Earth',
 '0781': 'Earth',
 '0782': 'Mars',
 '0784': 'Europa',
 '0785': 'Earth',
 '0786': 'Earth',
 '0787': 'Earth',
 '0788': 'Earth',
 '0789': 'Europa',
 '0790': 'Earth',
 '0791': 'Earth',
 '0793': 'Earth',
 '0794': 'Mars',
 '0795': 'Earth',
 '0796': 'Europa',
 '0797': 'Earth',
 '0798': 'Mars',
 '0799': 'Europa',
 '0802': 'Mars',
 '0805': 'Europa',
 '0806': 'Earth',
 '0808': 'Earth',
 '0809': 'Mars',
 '0811': 'Mars',
 '0813': 'Mars',
 '0815': 'Earth',
 '0816': 'Europa',
 '0817': 'Earth',
 '0818': 'Europa',
 '0819': 'Earth',
 '0820': 'Earth',
 '0822': 'Earth',
 '0823': 'Earth',
 '0824': 'Mars',
 '0825': 'Earth',
 '0826': 'Earth',
 '0828': 'Earth',
 '0829': 'Earth',
 '0830': 'Earth',
 '0833': 'Europa',
 '0834': 'Earth',
 '0835': 'Earth',
 '0836': 'Mars',
 '0839': 'Europa',
 '0840': 'Earth',
 '0845': 'Europa',
 '0846': 'Earth',
 '0848': 'Mars',
 '0849': 'Europa',
 '0850': 'Mars',
 '0851': 'Earth',
 '0859': 'Earth',
 '0860': 'Earth',
 '0863': 'Earth',
 '0865': 'Europa',
 '0867': 'Earth',
 '0868': 'Earth',
 '0869': 'Earth',
 '0870': 'Earth',
 '0871': 'Europa',
 '0873': 'Earth',
 '0874': 'Earth',
 '0875': 'Earth',
 '0876': 'Earth',
 '0877': 'Europa',
 '0878': 'Mars',
 '0879': 'Earth',
 '0881': 'Europa',
 '0883': 'Earth',
 '0885': 'Earth',
 '0889': 'Europa',
 '0890': 'Mars',
 '0893': 'Earth',
 '0898': 'Earth',
 '0899': 'Earth',
 '0901': 'Mars',
 '0902': 'Earth',
 '0903': 'Earth',
 '0904': 'Europa',
 '0905': 'Mars',
 '0906': 'Earth',
 '0907': 'Europa',
 '0910': 'Earth',
 '0911': 'Mars',
 '0912': 'Europa',
 '0913': 'Europa',
 '0915': 'Earth',
 '0918': 'Earth',
 '0919': 'Earth',
 '0921': 'Earth',
 '0922': 'Europa',
 '0923': 'Europa',
 '0924': 'Earth',
 '0925': 'Mars',
 '0926': 'Europa',
 '0927': 'Earth',
 '0928': 'Earth',
 '0930': 'Earth',
 '0931': 'Earth',
 '0932': 'Mars',
 '0933': 'Europa',
 '0935': 'Earth',
 '0938': 'Earth',
 '0939': 'Earth',
 '0940': 'Earth',
 '0941': 'Earth',
 '0942': 'Mars',
 '0944': 'Earth',
 '0946': 'Earth',
 '0947': 'Earth',
 '0949': 'Earth',
 '0951': 'Earth',
 '0952': 'Mars',
 '0953': 'Earth',
 '0955': 'Earth',
 '0956': 'Earth',
 '0957': 'Mars',
 '0960': 'Earth',
 '0961': 'Earth',
 '0964': 'Europa',
 '0965': 'Mars',
 '0966': 'Earth',
 '0968': 'Earth',
 '0969': 'Mars',
 '0970': 'Earth',
 '0971': 'Earth',
 '0972': 'Earth',
 '0975': 'Earth',
 '0976': 'Earth',
 '0978': 'Earth',
 '0979': 'Europa',
 '0982': 'Earth',
 '0983': 'Earth',
 '0984': 'Earth',
 '0985': 'Earth',
 '0987': 'Earth',
 '0988': 'Earth',
 '0989': 'Earth',
 '0990': 'Earth',
 '0991': 'Earth',
 '0992': 'Europa',
 '0993': 'Earth',
 '0994': 'Earth',
 '0995': 'Europa',
 '0997': 'Mars',
 '0998': 'Europa',
 '1000': 'Mars',
 '1001': 'Earth',
 '1002': 'Mars',
 '1004': 'Europa',
 '1005': 'Earth',
 '1006': 'Earth',
 '1008': 'Europa',
 '1011': 'Earth',
 '1012': 'Earth',
 '1013': 'Earth',
 '1014': 'Mars',
 '1015': 'Earth',
 '1017': 'Earth',
 '1018': 'Earth',
 '1019': 'Earth',
 '1020': 'Mars',
 '1022': 'Earth',
 '1024': 'Earth',
 '1025': 'Earth',
 '1026': 'Earth',
 '1027': 'Mars',
 '1029': 'Mars',
 '1030': 'Earth',
 '1031': 'Earth',
 '1032': 'Earth',
 '1033': 'Earth',
 '1034': 'Earth',
 '1035': 'Mars',
 '1036': 'Earth',
 '1038': 'Earth',
 '1040': 'Earth',
 '1041': 'Europa',
 '1043': 'Earth',
 '1045': 'Europa',
 '1046': 'Earth',
 '1047': 'Earth',
 '1048': 'Earth',
 '1049': 'Mars',
 '1051': 'Earth',
 '1052': 'Earth',
 '1053': 'Earth',
 '1054': 'Earth',
 '1056': 'Mars',
 '1057': 'Europa',
 '1058': 'Earth',
 '1060': 'Earth',
 '1062': 'Earth',
 '1063': 'Europa',
 '1065': 'Mars',
 '1066': 'Mars',
 '1068': 'Earth',
 '1075': 'Europa',
 '1076': 'Earth',
 '1077': 'Earth',
 '1078': 'Earth',
 '1079': 'Earth',
 '1080': 'Mars',
 '1082': 'Mars',
 '1083': 'Mars',
 '1084': 'Earth',
 '1085': 'Earth',
 '1086': 'Earth',
 '1088': 'Earth',
 '1089': 'Europa',
 '1091': 'Mars',
 '1093': 'Mars',
 '1094': 'Earth',
 '1095': 'Europa',
 '1096': 'Earth',
 '1097': 'Mars',
 '1099': 'Earth',
 '1100': 'Mars',
 '1102': 'Mars',
 '1105': 'Earth',
 '1108': 'Mars',
 '1110': 'Europa',
 '1112': 'Europa',
 '1113': 'Earth',
 '1114': 'Mars',
 '1115': 'Earth',
 '1116': 'Earth',
 '1117': 'Earth',
 '1121': 'Earth',
 '1123': 'Europa',
 '1127': 'Europa',
 '1129': 'Earth',
 '1130': 'Mars',
 '1132': 'Earth',
 '1133': 'Mars',
 '1134': 'Europa',
 '1136': 'Earth',
 '1140': 'Europa',
 '1141': 'Earth',
 '1142': 'Earth',
 '1144': 'Earth',
 '1146': 'Earth',
 '1147': 'Europa',
 '1148': 'Europa',
 '1149': 'Earth',
 '1150': 'Earth',
 '1152': 'Mars',
 '1153': 'Earth',
 '1154': 'Europa',
 '1155': 'Earth',
 '1156': 'Europa',
 '1161': 'Europa',
 '1162': 'Europa',
 '1163': 'Earth',
 '1165': 'Europa',
 '1166': 'Europa',
 '1167': 'Mars',
 '1168': 'Earth',
 '1169': 'Mars',
 '1170': 'Earth',
 '1173': 'Earth',
 '1174': 'Earth',
 '1175': 'Mars',
 '1177': 'Europa',
 '1178': 'Earth',
 '1179': 'Europa',
 '1180': 'Earth',
 '1182': 'Mars',
 '1185': 'Mars',
 '1186': 'Earth',
 '1187': 'Earth',
 '1188': 'Europa',
 '1190': 'Earth',
 '1191': 'Earth',
 '1192': 'Earth',
 '1193': 'Europa',
 '1195': 'Earth',
 '1197': 'Europa',
 '1198': 'Mars',
 '1199': 'Earth',
 '1203': 'Europa',
 '1206': 'Earth',
 '1208': 'Earth',
 '1210': 'Earth',
 '1211': 'Earth',
 '1212': 'Earth',
 '1213': 'Earth',
 '1214': 'Earth',
 '1215': 'Earth',
 '1216': 'Earth',
 '1218': 'Earth',
 '1220': 'Europa',
 '1221': 'Earth',
 '1222': 'Earth',
 '1223': 'Europa',
 '1225': 'Earth',
 '1228': 'Mars',
 '1229': 'Earth',
 '1230': 'Earth',
 '1231': 'Mars',
 '1232': 'Europa',
 '1233': 'Earth',
 '1234': 'Earth',
 '1235': 'Earth',
 '1236': 'Earth',
 '1238': 'Europa',
 '1239': 'Earth',
 '1240': 'Earth',
 '1242': 'Europa',
 '1243': 'Europa',
 '1246': 'Earth',
 '1248': 'Earth',
 '1250': 'Earth',
 '1254': 'Mars',
 '1255': 'Mars',
 '1256': 'Mars',
 '1258': 'Europa',
 '1259': 'Earth',
 '1260': 'Earth',
 '1261': 'Europa',
 '1263': 'Mars',
 '1264': 'Earth',
 '1267': 'Earth',
 '1269': 'Mars',
 '1271': 'Earth',
 '1273': 'Earth',
 '1274': 'Earth',
 '1278': 'Earth',
 '1279': 'Europa',
 '1280': 'Earth',
 '1281': 'Earth',
 '1282': 'Earth',
 '1283': 'Earth',
 '1284': 'Mars',
 '1285': 'Earth',
 '1286': 'Mars',
 '1287': 'Mars',
 '1288': 'Earth',
 '1289': 'Earth',
 '1291': 'Mars',
 '1292': 'Europa',
 '1293': 'Earth',
 '1294': 'Europa',
 '1295': 'Earth',
 '1299': 'Earth',
 '1300': 'Earth',
 '1302': 'Mars',
 '1304': 'Earth',
 '1306': 'Europa',
 '1307': 'Earth',
 '1308': 'Europa',
 '1309': 'Earth',
 '1310': 'Europa',
 '1311': 'Mars',
 '1312': 'Earth',
 '1316': 'Europa',
 '1317': 'Mars',
 '1322': 'Earth',
 '1323': 'Earth',
 '1324': 'Earth',
 '1325': 'Earth',
 '1326': 'Mars',
 '1328': 'Earth',
 '1330': 'Mars',
 '1331': 'Earth',
 '1332': 'Earth',
 '1333': 'Earth',
 '1335': 'Earth',
 '1336': 'Earth',
 '1337': 'Earth',
 '1340': 'Earth',
 '1342': 'Earth',
 '1345': 'Earth',
 '1348': 'Europa',
 '1350': 'Earth',
 '1351': 'Earth',
 '1352': 'Mars',
 '1353': 'Mars',
 '1355': 'Earth',
 '1356': 'Earth',
 '1357': 'Mars',
 '1360': 'Earth',
 '1362': 'Earth',
 '1365': 'Europa',
 '1366': 'Earth',
 '1368': 'Earth',
 '1370': 'Earth',
 '1371': 'Mars',
 '1375': 'Earth',
 '1376': 'Earth',
 '1377': 'Europa',
 '1378': 'Earth',
 '1379': 'Earth',
 '1380': 'Europa',
 '1381': 'Earth',
 '1382': 'Earth',
 '1383': 'Europa',
 '1384': 'Earth',
 '1386': 'Earth',
 '1387': 'Mars',
 '1389': 'Earth',
 '1390': 'Earth',
 '1391': 'Mars',
 '1393': 'Mars',
 '1395': 'Earth',
 '1397': 'Earth',
 '1398': 'Earth',
 '1399': 'Earth',
 '1400': 'Earth',
 '1401': 'Earth',
 '1402': 'Earth',
 '1403': 'Earth',
 '1404': 'Europa',
 '1406': 'Mars',
 '1407': 'Earth',
 '1408': 'Earth',
 '1410': 'Earth',
 '1412': 'Earth',
 '1413': 'Earth',
 '1414': 'Earth',
 '1415': 'Europa',
 '1416': 'Earth',
 '1417': 'Europa',
 '1419': 'Mars',
 '1420': 'Mars',
 '1421': 'Mars',
 '1423': 'Europa',
 '1424': 'Europa',
 '1425': 'Earth',
 '1426': 'Europa',
 '1427': 'Mars',
 '1428': 'Earth',
 '1430': 'Earth',
 '1431': 'Earth',
 '1433': 'Earth',
 '1434': 'Earth',
 '1435': 'Earth',
 '1438': 'Earth',
 '1439': 'Mars',
 '1440': 'Earth',
 '1442': 'Earth',
 '1443': 'Earth',
 '1444': 'Europa',
 '1445': 'Earth',
 '1447': 'Earth',
 '1450': 'Europa',
 '1451': 'Europa',
 '1452': 'Europa',
 '1453': 'Earth',
 '1454': 'Europa',
 '1455': 'Europa',
 '1457': 'Earth',
 '1460': 'Earth',
 '1461': 'Earth',
 '1462': 'Earth',
 '1463': 'Earth',
 '1465': 'Earth',
 '1474': 'Mars',
 '1478': 'Earth',
 '1479': 'Mars',
 '1481': 'Mars',
 '1484': 'Earth',
 '1485': 'Mars',
 '1488': 'Mars',
 '1489': 'Earth',
 '1490': 'Europa',
 '1491': 'Earth',
 '1493': 'Earth',
 '1498': 'Earth',
 '1499': 'Earth',
 '1500': 'Earth',
 '1501': 'Earth',
 '1503': 'Mars',
 '1506': 'Earth',
 '1507': 'Earth',
 '1509': 'Mars',
 '1510': 'Mars',
 '1511': 'Europa',
 '1515': 'Earth',
 '1520': 'Earth',
 '1521': 'Mars',
 '1523': 'Europa',
 '1524': 'Earth',
 '1525': 'Mars',
 '1526': 'Earth',
 '1527': 'Europa',
 '1528': 'Mars',
 '1529': 'Europa',
 '1531': 'Earth',
 ...}

In [138]:
train['HomePlanet'].fillna(train['Group'].map(home_dict), inplace = True)

---

In [139]:
train['familyname'] = train['Name'].str.split(' ').str[-1]

In [140]:
name_group = train.groupby(['familyname', 'HomePlanet']).size().reset_index()

In [141]:
name_dict = {}

for k, v in zip(name_group['familyname'], name_group['HomePlanet']):
    name_dict[k] = v

In [142]:
name_dict

{'Acobson': 'Earth',
 'Acobsond': 'Earth',
 'Adavisons': 'Earth',
 'Adkinson': 'Earth',
 'Admingried': 'Europa',
 'Aginge': 'Europa',
 'Ailled': 'Europa',
 'Aillyber': 'Europa',
 'Aiming': 'Europa',
 'Ainatint': 'Europa',
 'Aindlylid': 'Europa',
 'Ainserfle': 'Europa',
 'Airdring': 'Europa',
 'Aivering': 'Europa',
 'Alaring': 'Europa',
 'Alaxed': 'Europa',
 'Alberts': 'Earth',
 'Alcemblery': 'Europa',
 'Alenat': 'Europa',
 'Alenter': 'Europa',
 'Alentonway': 'Earth',
 'Alest': 'Earth',
 'Alfordonard': 'Earth',
 'Alindiveng': 'Europa',
 'Alldson': 'Earth',
 'Aloubtled': 'Europa',
 'Alshipson': 'Earth',
 'Alvasquez': 'Earth',
 'Alvercal': 'Europa',
 'Alvesssidy': 'Europa',
 'Ambleetive': 'Europa',
 'Ambleeve': 'Europa',
 'Amblereld': 'Europa',
 'Ametic': 'Europa',
 'Amincrerus': 'Europa',
 'Amonsmane': 'Europa',
 'Amonysidle': 'Europa',
 'Amoutake': 'Europa',
 'Amspring': 'Europa',
 'Anake': 'Mars',
 'Anche': 'Mars',
 'Ancontaked': 'Europa',
 'Ancy': 'Mars',
 'Andackson': 'Earth',
 'Anderking': 'Europa',
 'Andley': 'Earth',
 'Ane': 'Mars',
 'Aneetle': 'Europa',
 'Aneter': 'Europa',
 'Anindery': 'Europa',
 'Anpie': 'Mars',
 'Antcal': 'Europa',
 'Anthompson': 'Earth',
 'Anthon': 'Earth',
 'Antoshipson': 'Earth',
 'Apeau': 'Mars',
 'Apedishaft': 'Europa',
 'Apenelexy': 'Europa',
 'Apie': 'Mars',
 'Appie': 'Mars',
 'Apple': 'Mars',
 'Arible': 'Europa',
 'Armstromez': 'Earth',
 'Arner': 'Earth',
 'Arneras': 'Earth',
 'Aroodint': 'Europa',
 'Arterate': 'Europa',
 'Ashipeck': 'Earth',
 'Ashipson': 'Earth',
 'Asivetfuel': 'Europa',
 'Asolipery': 'Europa',
 'Asoppor': 'Europa',
 'Assibler': 'Europa',
 'Asticit': 'Europa',
 'Atkinney': 'Earth',
 'Ausivetpul': 'Europa',
 'Avidson': 'Earth',
 'Avisley': 'Earth',
 'Avisnydes': 'Earth',
 'Axlentindy': 'Europa',
 'Ayalazquez': 'Earth',
 'Babre': 'Mars',
 'Bache': 'Mars',
 'Baciffhaut': 'Europa',
 'Bacistion': 'Europa',
 'Backe': 'Mars',
 'Bagetvable': 'Europa',
 'Bagint': 'Europa',
 'Bailes': 'Earth',
 'Bairdford': 'Earth',
 'Bairdyork': 'Earth',
 'Bake': 'Mars',
 'Bakericks': 'Earth',
 'Bakerrison': 'Earth',
 'Bakerson': 'Earth',
 'Baketton': 'Earth',
 'Baldens': 'Earth',
 'Balderts': 'Earth',
 'Baldson': 'Earth',
 'Baleful': 'Europa',
 'Balightal': 'Europa',
 'Balle': 'Mars',
 'Ballexy': 'Europa',
 'Balley': 'Earth',
 'Ballocks': 'Earth',
 'Ban': 'Mars',
 'Bancy': 'Mars',
 'Bane': 'Mars',
 'Banie': 'Mars',
 'Bara': 'Mars',
 'Barberts': 'Earth',
 'Barbes': 'Earth',
 'Bardina': 'Earth',
 'Bardinard': 'Earth',
 'Bardsey': 'Earth',
 'Bardson': 'Earth',
 'Barkeretton': 'Earth',
 'Barks': 'Earth',
 'Barles': 'Earth',
 'Barmant': 'Europa',
 'Barne': 'Mars',
 'Barnolaney': 'Earth',
 'Barnoldeney': 'Earth',
 'Barnolderg': 'Earth',
 'Barrelliver': 'Earth',
 'Barrez': 'Earth',
 'Barrilloney': 'Earth',
 'Barris': 'Earth',
 'Barrison': 'Earth',
 'Bart': 'Mars',
 'Barte': 'Mars',
 'Bartez': 'Earth',
 'Bartines': 'Earth',
 'Bartins': 'Earth',
 'Bate': 'Mars',
 'Batestonley': 'Earth',
 'Batte': 'Mars',
 'Batthewitt': 'Earth',
 'Bau': 'Mars',
 'Baxters': 'Earth',
 'Baxterson': 'Earth',
 'Beachez': 'Earth',
 'Beake': 'Mars',
 'Bealvewd': 'Europa',
 'Beangley': 'Earth',
 'Bears': 'Earth',
 'Beasleyes': 'Earth',
 'Beckeetter': 'Earth',
 'Beckeey': 'Earth',
 'Beckerson': 'Earth',
 'Bedectical': 'Europa',
 'Beling': 'Europa',
 'Bellarkerd': 'Earth',
 'Belley': 'Earth',
 'Bellyonsley': 'Earth',
 'Belstrut': 'Europa',
 'Benderez': 'Earth',
 'Benney': 'Earth',
 'Bensley': 'Earth',
 'Berges': 'Earth',
 'Berle': 'Mars',
 'Berreranks': 'Earth',
 'Bert': 'Mars',
 'Berte': 'Mars',
 'Bertiz': 'Earth',
 'Bertsontry': 'Earth',
 'Beston': 'Earth',
 'Betie': 'Mars',
 'Bette': 'Mars',
 'Bewarsecal': 'Europa',
 'Biba': 'Mars',
 'Bine': 'Mars',
 'Binie': 'Mars',
 'Birds': 'Earth',
 'Birt': 'Mars',
 'Birte': 'Mars',
 'Bla': 'Mars',
 'Blace': 'Earth',
 'Blacks': 'Earth',
 'Blainson': 'Earth',
 'Blake': 'Mars',
 'Blan': 'Mars',
 'Blancoy': 'Earth',
 'Blandez': 'Earth',
 'Blane': 'Mars',
 'Blange': 'Earth',
 'Blangibson': 'Earth',
 'Blanglison': 'Earth',
 'Blanspe': 'Europa',
 'Blate': 'Mars',
 'Ble': 'Mars',
 'Blees': 'Mars',
 'Bleling': 'Europa',
 'Blentrary': 'Europa',
 'Blercat': 'Europa',
 'Blie': 'Mars',
 'Blité': 'Mars',
 'Boderbint': 'Europa',
 'Boltertley': 'Earth',
 'Boltond': 'Earth',
 'Boltund': 'Europa',
 'Bonder': 'Earth',
 'Bonnondry': 'Earth',
 'Bookerson': 'Earth',
 'Bookson': 'Earth',
 'Bookst': 'Earth',
 'Booneid': 'Earth',
 'Booness': 'Earth',
 'Booters': 'Earth',
 'Bootez': 'Earth',
 'Bootious': 'Europa',
 'Bootty': 'Europa',
 'Bost': 'Mars',
 'Boste': 'Mars',
 'Bota': 'Mars',
 'Botie': 'Mars',
 'Botte': 'Mars',
 'Bowenasey': 'Earth',
 'Bowerson': 'Earth',
 'Boyers': 'Earth',
 'Boyerson': 'Earth',
 'Boyersons': 'Earth',
 'Boyst': 'Mars',
 'Bra': 'Mars',
 'Bradamss': 'Earth',
 'Bradiary': 'Europa',
 'Bradissive': 'Europa',
 'Bradlerson': 'Earth',
 'Brailidy': 'Europa',
 'Brakebarne': 'Europa',
 'Brakeded': 'Europa',
 'Brakeng': 'Europa',
 'Brakepined': 'Europa',
 'Brakeril': 'Europa',
 'Braned': 'Europa',
 'Brantcable': 'Europa',
 'Brantuarez': 'Earth',
 'Brathful': 'Europa',
 'Braymon': 'Earth',
 'Brazo': 'Mars',
 'Bre': 'Mars',
 'Breke': 'Mars',
 'Brele': 'Mars',
 'Brenney': 'Earth',
 'Brensonsen': 'Earth',
 'Brie': 'Mars',
 'Briggins': 'Earth',
 'Briggston': 'Earth',
 'Brightez': 'Earth',
 'Brighttt': 'Earth',
 'Brin': 'Mars',
 'Brine': 'Mars',
 'Briouse': 'Europa',
 'Brity': 'Mars',
 'Brooke': 'Earth',
 'Brookenson': 'Earth',
 'Brooker': 'Earth',
 'Brookes': 'Earth',
 'Browlerson': 'Earth',
 'Brownings': 'Earth',
 'Brownson': 'Earth',
 'Brugashed': 'Europa',
 'Bruthydre': 'Europa',
 'Bryangton': 'Earth',
 'Bryants': 'Earth',
 'Buchansen': 'Earth',
 'Buche': 'Mars',
 'Buckeelez': 'Earth',
 'Buckeenez': 'Earth',
 'Buckentry': 'Earth',
 'Bucklandez': 'Earth',
 'Buckleinson': 'Earth',
 'Bucknersony': 'Earth',
 'Buckson': 'Earth',
 'Buko': 'Mars',
 'Bullerson': 'Earth',
 'Bulliamoses': 'Earth',
 'Bullisey': 'Earth',
 'Bun': 'Mars',
 'Buncy': 'Mars',
 'Burcaling': 'Europa',
 'Burchanez': 'Earth',
 'Burchard': 'Earth',
 'Burchrison': 'Earth',
 'Burie': 'Mars',
 'Burker': 'Earth',
 'Burksson': 'Earth',
 'Burle': 'Mars',
 'Burnerez': 'Earth',
 'Burnewman': 'Earth',
 'Burraymons': 'Earth',
 'Burrilllins': 'Earth',
 'Burry': 'Mars',
 'Burryerson': 'Earth',
 'Burta': 'Mars',
 'Burte': 'Mars',
 'Burtiz': 'Earth',
 'Bush': 'Mars',
 'Bushafford': 'Earth',
 'Bushallert': 'Earth',
 'Bushins': 'Earth',
 'Busive': 'Europa',
 'Buth': 'Mars',
 'Buthe': 'Mars',
 'Butte': 'Mars',
 'Butty': 'Mars',
 'Byerry': 'Earth',
 'Byerson': 'Earth',
 'Byerton': 'Earth',
 'Cabraseed': 'Europa',
 'Cabrewsond': 'Earth',
 'Caineson': 'Earth',
 'Cainghannon': 'Earth',
 'Cake': 'Mars',
 'Cakie': 'Mars',
 'Cako': 'Mars',
 'Calazy': 'Europa',
 'Calhounez': 'Earth',
 'Calian': 'Europa',
 'Caljoiry': 'Europa',
 'Callower': 'Europa',
 'Callowery': 'Earth',
 'Caltilter': 'Europa',
 'Calved': 'Europa',
 'Camerrison': 'Earth',
 'Cames': 'Earth',
 'Caming': 'Europa',
 'Campson': 'Earth',
 'Can': 'Mars',
 'Canie': 'Mars',
 'Canields': 'Earth',
 'Canton': 'Earth',
 'Capplid': 'Europa',
 'Cardner': 'Earth',
 'Cardners': 'Earth',
 'Cardsay': 'Earth',
 'Carezquez': 'Earth',
 'Carlsonney': 'Earth',
 'Carpennels': 'Earth',
 'Carpentley': 'Earth',
 'Carreralend': 'Earth',
 'Carrishley': 'Earth',
 'Carsoning': 'Earth',
 'Cart': 'Mars',
 'Carterson': 'Earth',
 'Cartez': 'Earth',
 'Cartiz': 'Earth',
 'Cartyernan': 'Earth',
 'Cartz': 'Earth',
 'Carté': 'Mars',
 'Carverson': 'Earth',
 'Carvis': 'Earth',
 'Casentry': 'Earth',
 'Casez': 'Earth',
 'Casonston': 'Earth',
 'Cassiding': 'Europa',
 'Castannison': 'Earth',
 'Castery': 'Europa',
 'Castron': 'Earth',
 'Casty': 'Mars',
 'Cathome': 'Europa',
 'Catimod': 'Europa',
 'Cattle': 'Europa',
 'Cattyried': 'Europa',
 'Cha': 'Mars',
 'Chaellerty': 'Earth',
 'Chake': 'Mars',
 'Chanan': 'Earth',
 'Chanash': 'Earth',
 'Chapmaney': 'Earth',
 'Chardsonnon': 'Earth',
 'Chardsons': 'Earth',
 'Chardst': 'Earth',
 'Charpelaney': 'Earth',
 'Charryerry': 'Earth',
 'Chasey': 'Earth',
 'Chate': 'Mars',
 'Chavezalez': 'Earth',
 'Chcak': 'Mars',
 'Che': 'Mars',
 'Cheen': 'Mars',
 'Chen': 'Mars',
 'Chene': 'Mars',
 'Chenson': 'Earth',
 'Ches': 'Mars',
 'Chhaft': 'Europa',
 'Chica': 'Mars',
 'Chiff': 'Mars',
 'Chité': 'Mars',
 'Chmad': 'Mars',
 'Chman': 'Mars',
 'Chnik': 'Mars',
 'Chocaters': 'Europa',
 'Chort': 'Mars',
 'Chpeng': 'Europa',
 'Chpie': 'Mars',
 'Chrie': 'Mars',
 'Chroeders': 'Earth',
 'Chsere': 'Europa',
 'Chuble': 'Europa',
 'Cientteng': 'Europa',
 'Ciplanke': 'Europa',
 'Cisorter': 'Europa',
 'Cla': 'Mars',
 'Clake': 'Mars',
 'Clarty': 'Europa',
 'Clayson': 'Earth',
 'Cle': 'Mars',
 'Cleachrand': 'Earth',
 'Clean': 'Earth',
 'Cleang': 'Earth',
 'Cleman': 'Earth',
 'Cleminglas': 'Earth',
 'Clemondsey': 'Earth',
 'Clidly': 'Europa',
 'Clinantones': 'Earth',
 'Clinarfork': 'Europa',
 'Clindy': 'Europa',
 'Clugeadry': 'Europa',
 'Clugeammy': 'Europa',
 'Clugete': 'Europa',
 'Clughted': 'Europa',
 'Clugnobse': 'Europa',
 'Clumshangs': 'Europa',
 'Clumsty': 'Europa',
 'Clunic': 'Europa',
 'Clutcheed': 'Europa',
 'Clutchor': 'Europa',
 'Cluted': 'Europa',
 'Cluthosexy': 'Europa',
 'Clutolded': 'Europa',
 'Coarswing': 'Europa',
 'Cobson': 'Earth',
 'Cochrisons': 'Earth',
 'Cofferson': 'Earth',
 'Coffmaney': 'Earth',
 'Coflé': 'Mars',
 'Cohendright': 'Earth',
 'Coictrazy': 'Europa',
 'Coillery': 'Europa',
 'Cola': 'Mars',
 'Colensid': 'Europa',
 'Coley': 'Earth',
 'Coleyanglas': 'Earth',
 'Colle': 'Mars',
 'Colleruces': 'Earth',
 'Collinson': 'Earth',
 'Colomonson': 'Earth',
 'Colte': 'Mars',
 'Combson': 'Earth',
 'Comessic': 'Europa',
 'Conable': 'Europa',
 'Conablese': 'Europa',
 'Conachets': 'Europa',
 'Conale': 'Europa',
 'Conaly': 'Europa',
 'Conamminal': 'Europa',
 'Conate': 'Europa',
 'Conca': 'Mars',
 'Concy': 'Mars',
 'Cone': 'Mars',
 'Conie': 'Mars',
 'Coning': 'Europa',
 'Coniple': 'Europa',
 'Conleydenan': 'Earth',
 'Connelson': 'Earth',
 'Conney': 'Earth',
 'Connon': 'Earth',
 'Contery': 'Europa',
 'Contrevins': 'Earth',
 'Cookentaney': 'Earth',
 'Cooki': 'Mars',
 'Cooks': 'Earth',
 'Cookson': 'Earth',
 'Coolerson': 'Earth',
 'Coolez': 'Earth',
 'Coopelandez': 'Earth',
 'Cooperkins': 'Earth',
 'Coopezmaney': 'Earth',
 'Corie': 'Mars',
 'Corman': 'Earth',
 'Cort': 'Mars',
 'Corte': 'Mars',
 'Cotik': 'Mars',
 'Cotte': 'Mars',
 'Coudered': 'Europa',
 'Coune': 'Mars',
 'Couresteer': 'Europa',
 'Couseced': 'Europa',
 'Cousel': 'Europa',
 'Coustive': 'Europa',
 'Covale': 'Europa',
 'Covetive': 'Europa',
 'Coweboded': 'Europa',
 'Cowsearney': 'Europa',
 'Cowtale': 'Europa',
 'Coxterez': 'Earth',
 'Cracionfic': 'Europa',
 'Craftstens': 'Earth',
 'Craing': 'Europa',
 'Crakenecal': 'Europa',
 'Crakete': 'Europa',
 'Craleve': 'Europa',
 'Cralinal': 'Europa',
 'Crantiale': 'Europa',
 'Cratrave': 'Europa',
 'Crayeson': 'Earth',
 'Cre': 'Mars',
 'Cread': 'Mars',
 'Creke': 'Mars',
 'Crelaxle': 'Europa',
 'Cres': 'Mars',
 'Crie': 'Mars',
 'Crioncery': 'Europa',
 'Crité': 'Mars',
 'Crosarios': 'Earth',
 'Crosbornes': 'Earth',
 'Crueld': 'Europa',
 'Cruzaley': 'Earth',
 'Cry': 'Mars',
 'Cuche': 'Mars',
 'Cumpting': 'Europa',
 'Cuplial': 'Europa',
 'Cure': 'Mars',
 'Curie': 'Mars',
 'Curle': 'Mars',
 'Currisones': 'Earth',
 'Curry': 'Mars',
 'Curte': 'Mars',
 'Curton': 'Earth',
 'Cusa': 'Mars',
 'Cylistrand': 'Europa',
 'Dake': 'Mars',
 'Dal': 'Mars',
 'Dan': 'Mars',
 'Danad': 'Mars',
 'Danielps': 'Earth',
 'Date': 'Mars',
 'Datie': 'Mars',
 'Dato': 'Mars',
 'Datte': 'Mars',
 'Datty': 'Mars',
 'Daughessey': 'Earth',
 'Daughtson': 'Earth',
 'Daughttley': 'Earth',
 'Davens': 'Earth',
 'Daviddley': 'Earth',
 'Davispinoz': 'Earth',
 'Dawsoncis': 'Earth',
 'Dayers': 'Earth',
 'Deckerson': 'Earth',
 'Deckley': 'Earth',
 'Dectory': 'Europa',
 'Dedentive': 'Europa',
 'Dedinder': 'Europa',
 'Dedometeel': 'Europa',
 'Deeke': 'Mars',
 'Delangleton': 'Earth',
 'Delazarson': 'Earth',
 'Delez': 'Earth',
 'Demansty': 'Europa',
 'Denashipson': 'Earth',
 'Depie': 'Mars',
 'Derry': 'Mars',
 'Derte': 'Mars',
 'Dertering': 'Europa',
 'Derterval': 'Europa',
 'Dervalt': 'Europa',
 'Deryplinet': 'Europa',
 'Deva': 'Mars',
 'Diabysid': 'Europa',
 'Dianket': 'Europa',
 'Diateous': 'Europa',
 'Diazarez': 'Earth',
 'Dicely': 'Europa',
 'Dickley': 'Earth',
 'Dickman': 'Earth',
 'Dicksons': 'Earth',
 'Dicomeng': 'Europa',
 'Dightent': 'Europa',
 'Dillestron': 'Earth',
 'Dillines': 'Earth',
 'Dillips': 'Earth',
 'Dindeng': 'Europa',
 'Dingauge': 'Europa',
 'Dinger': 'Europa',
 'Dinsprody': 'Europa',
 'Diouselt': 'Europa',
 'Dischod': 'Europa',
 'Discuous': 'Europa',
 'Disgul': 'Europa',
 'Dishearly': 'Europa',
 'Disheract': 'Europa',
 'Dishocatal': 'Europa',
 'Disight': 'Europa',
 'Disivering': 'Europa',
 'Dissper': 'Europa',
 'Disteady': 'Europa',
 'Dister': 'Europa',
 'Distured': 'Europa',
 'Dombsoney': 'Earth',
 'Domington': 'Earth',
 'Dompreced': 'Europa',
 'Donotaked': 'Europa',
 'Donson': 'Earth',
 'Doorge': 'Europa',
 'Dorsenry': 'Earth',
 'Dotsondez': 'Earth',
 'Doughan': 'Earth',
 'Douglasen': 'Earth',
 'Drakeekss': 'Earth',
 'Dratembid': 'Europa',
 'Drayfulery': 'Europa',
 'Dreamspric': 'Europa',
 'Drelcate': 'Europa',
 'Dressink': 'Europa',
 'Drivery': 'Europa',
 'Droning': 'Europa',
 'Duckil': 'Europa',
 'Duffmaney': 'Earth',
 'Dukertyler': 'Earth',
 'Dun': 'Mars',
 'Duncy': 'Mars',
 'Dunnisey': 'Earth',
 'Duranks': 'Earth',
 'Dutte': 'Mars',
 'Dutty': 'Mars',
 'Dyers': 'Earth',
 'Dynatic': 'Europa',
 'Dynigic': 'Europa',
 'Earmeter': 'Europa',
 'Ecart': 'Mars',
 'Ecate': 'Mars',
 'Eccle': 'Mars',
 'Ecre': 'Mars',
 'Edwartizman': 'Earth',
 'Efulows': 'Europa',
 'Eguing': 'Europa',
 'Ellahan': 'Earth',
 'Ellcefulve': 'Europa',
 'Ellson': 'Earth',
 'Embleng': 'Europa',
 'Emead': 'Mars',
 'Emenez': 'Earth',
 'Emetillove': 'Europa',
 'Emone': 'Mars',
 'Emoted': 'Europa',
 'Empie': 'Mars',
 'Eneurordry': 'Europa',
 'Englas': 'Earth',
 'Englence': 'Earth',
 'Ennalve': 'Europa',
 'Entedraved': 'Europa',
 'Entenedy': 'Europa',
 'Entratable': 'Europa',
 'Erflé': 'Mars',
 'Ericksonga': 'Earth',
 'Erle': 'Mars',
 'Erpie': 'Mars',
 'Erry': 'Mars',
 'Erte': 'Mars',
 'Esseal': 'Europa',
 'Estein': 'Earth',
 'Estevesters': 'Earth',
 'Estiagosen': 'Earth',
 'Estron': 'Earth',
 'Evedorsen': 'Earth',
 'Ewins': 'Earth',
 'Ewisentley': 'Earth',
 'Ewiseston': 'Earth',
 'Excialing': 'Europa',
 'Excionging': 'Europa',
 'Exhaft': 'Europa',
 'Exhaftearm': 'Europa',
 'Exible': 'Europa',
 'Exibuctich': 'Europa',
 'Exnutch': 'Europa',
 'Exnutchor': 'Europa',
 'Fache': 'Mars',
 'Facke': 'Mars',
 'Facle': 'Mars',
 'Fairdised': 'Europa',
 'Fanbox': 'Europa',
 'Fanchy': 'Europa',
 'Fandomatty': 'Europa',
 'Fanseld': 'Europa',
 'Fansty': 'Europa',
 'Farleyatton': 'Earth',
 'Farmonrada': 'Earth',
 'Farrez': 'Earth',
 'Farrowns': 'Earth',
 'Fatchanble': 'Europa',
 'Fate': 'Mars',
 'Fatte': 'Mars',
 'Fatted': 'Europa',
 'Fawnsive': 'Europa',
 'Femoused': 'Europa',
 'Fictful': 'Europa',
 'Fielsenders': 'Earth',
 'Fielson': 'Earth',
 'Figuez': 'Earth',
 'Fiha': 'Mars',
 'Filerst': 'Europa',
 'Fincy': 'Mars',
 'Fine': 'Mars',
 'Fisheparks': 'Earth',
 'Fisherry': 'Earth',
 'Fishopper': 'Earth',
 'Fisty': 'Mars',
 'Fisun': 'Mars',
 'Fitzgerson': 'Earth',
 'Fla': 'Mars',
 'Flaie': 'Mars',
 'Flake': 'Mars',
 'Flart': 'Mars',
 'Flate': 'Mars',
 'Flatic': 'Europa',
 'Fle': 'Mars',
 'Flell': 'Mars',
 'Flemaney': 'Earth',
 'Fles': 'Mars',
 'Flesping': 'Europa',
 'Fliblerolt': 'Europa',
 'Flie': 'Mars',
 'Flité': 'Mars',
 'Floaf': 'Mars',
 'Flourbent': 'Europa',
 'Floways': 'Earth',
 'Flowensley': 'Earth',
 'Floydendley': 'Earth',
 'Flyncharlan': 'Earth',
 'Flynner': 'Earth',
 'Flynney': 'Earth',
 'Flynnis': 'Earth',
 'Flé': 'Mars',
 'Foledges': 'Earth',
 'Folemonley': 'Earth',
 'Folhal': 'Europa',
 'Folkshbox': 'Europa',
 'Foller': 'Europa',
 'Folumorly': 'Europa',
 'Fone': 'Mars',
 'Fonie': 'Mars',
 'Foraud': 'Europa',
 'Fordulgaug': 'Europa',
 'Forne': 'Mars',
 'Forous': 'Europa',
 'Fort': 'Mars',
 'Fouseding': 'Europa',
 'Fowlaney': 'Earth',
 'Fowles': 'Earth',
 'Fowlesterez': 'Earth',
 'Foxter': 'Earth',
 'Frablerly': 'Europa',
 'Frakepeed': 'Europa',
 'Fralledic': 'Europa',
 'Franankson': 'Earth',
 'Franchaney': 'Earth',
 'Francock': 'Earth',
 'Frandriquez': 'Earth',
 'Franey': 'Earth',
 'Franton': 'Earth',
 'Frasp': 'Mars',
 'Frattyring': 'Europa',
 'Frazie': 'Earth',
 'Frazo': 'Mars',
 'Freder': 'Earth',
 'Frederry': 'Earth',
 'Fredersend': 'Earth',
 'Freednal': 'Europa',
 'Freevenson': 'Earth',
 'Freptic': 'Europa',
 'Frie': 'Mars',
 'Fringearty': 'Europa',
 'Fringh': 'Europa',
 'Frintful': 'Europa',
 'Frité': 'Mars',
 'Frogauded': 'Europa',
 'Frolestty': 'Europa',
 'Fruidy': 'Europa',
 'Fryan': 'Earth',
 'Fryersonis': 'Earth',
 'Fryes': 'Earth',
 'Fuelddid': 'Europa',
 'Fuelightic': 'Europa',
 'Fueling': 'Europa',
 'Fuelisent': 'Europa',
 'Fuenterson': 'Earth',
 'Fuentryoung': 'Earth',
 'Fulacid': 'Europa',
 'Fulatorly': 'Europa',
 'Fulazy': 'Europa',
 'Fuleng': 'Europa',
 'Fullided': 'Europa',
 'Fullous': 'Europa',
 'Fulloydez': 'Earth',
 'Fulous': 'Europa',
 'Fultz': 'Earth',
 'Fushausive': 'Europa',
 'Fusimodent': 'Europa',
 'Gainebergan': 'Earth',
 'Gaineyerson': 'Earth',
 'Gaington': 'Earth',
 'Gainney': 'Earth',
 'Gallandez': 'Earth',
 'Gallard': 'Earth',
 'Gallencis': 'Earth',
 'Gallenry': 'Earth',
 'Galoquid': 'Europa',
 'Gamberson': 'Earth',
 'Gambs': 'Earth',
 'Garden': 'Earth',
 'Gardonadox': 'Earth',
 'Gardsondez': 'Earth',
 'Garnes': 'Earth',
 'Garnettiz': 'Earth',
 'Garrincent': 'Earth',
 'Garzaley': 'Earth',
 'Geadle': 'Europa',
 'Geakerat': 'Europa',
 'Gealably': 'Europa',
 'Gealloyalt': 'Europa',
 'Gealter': 'Europa',
 'Gearitte': 'Europa',
 'Geatenth': 'Europa',
 'Gecre': 'Mars',
 'Gele': 'Mars',
 'Gelie': 'Mars',
 'Gelle': 'Mars',
 'Gelte': 'Mars',
 'Gemoserad': 'Europa',
 'Gen': 'Mars',
 'Gency': 'Mars',
 'Gene': 'Mars',
 'Geneltic': 'Europa',
 'Gented': 'Europa',
 'Gentledges': 'Earth',
 'Genuild': 'Europa',
 'Geoconne': 'Europa',
 'Georgasey': 'Earth',
 'Geousker': 'Europa',
 'Geousty': 'Europa',
 'Gepie': 'Mars',
 'Geraing': 'Europa',
 'Gerin': 'Mars',
 'Gerry': 'Mars',
 'Giba': 'Mars',
 'Gibbsonton': 'Earth',
 'Gilesonston': 'Earth',
 'Giller': 'Earth',
 'Gilleranks': 'Earth',
 'Gilleyons': 'Earth',
 'Gillock': 'Earth',
 'Gin': 'Mars',
 'Gine': 'Mars',
 'Gleroling': 'Europa',
 'Glisormal': 'Europa',
 'Glogry': 'Europa',
 'Gloother': 'Europa',
 'Glousspidy': 'Europa',
 'Gloyanthy': 'Europa',
 'Gocent': 'Europa',
 'Goffey': 'Earth',
 'Goldendrice': 'Earth',
 'Gonzaley': 'Earth',
 'Goods': 'Earth',
 'Goodson': 'Earth',
 'Goody': 'Earth',
 'Gooki': 'Mars',
 'Goortedant': 'Europa',
 'Gordanieves': 'Earth',
 'Gordond': 'Earth',
 'Gouldensen': 'Earth',
 'Graciansus': 'Europa',
 'Grahangory': 'Earth',
 'Graie': 'Mars',
 'Graneyes': 'Earth',
 'Gre': 'Mars',
 'Gread': 'Mars',
 'Grean': 'Mars',
 'Greded': 'Europa',
 'Greenez': 'Earth',
 'Greeves': 'Earth',
 'Gregordy': 'Earth',
 'Grentual': 'Europa',
 'Gres': 'Mars',
 'Griffince': 'Earth',
 'Grifford': 'Earth',
 'Griffy': 'Earth',
 'Groforacid': 'Europa',
 'Guerson': 'Earth',
 'Guezaley': 'Earth',
 'Guieroolow': 'Europa',
 'Gulcepusy': 'Europa',
 'Guloofant': 'Europa',
 'Gulthler': 'Europa',
 'Hac': 'Mars',
 'Hacle': 'Mars',
 'Haftent': 'Europa',
 'Haftical': 'Europa',
 'Hahnstoneal': 'Earth',
 'Hahnstonsen': 'Earth',
 'Hake': 'Mars',
 'Hales': 'Earth',
 'Halexandez': 'Earth',
 'Hallahaney': 'Earth',
 'Hamberterry': 'Earth',
 'Hamcmahon': 'Earth',
 'Hammons': 'Earth',
 'Hammonton': 'Earth',
 'Handertiz': 'Earth',
 'Hanghanson': 'Earth',
 'Hanner': 'Earth',
 'Hapie': 'Mars',
 'Hardley': 'Earth',
 'Hardonald': 'Earth',
 'Hardson': 'Earth',
 'Hardsonerry': 'Earth',
 'Hariourcal': 'Europa',
 'Harley': 'Earth',
 'Harmond': 'Earth',
 'Harmontry': 'Earth',
 'Harperez': 'Earth',
 'Harrenoldez': 'Earth',
 'Harry': 'Earth',
 'Hart': 'Mars',
 'Harta': 'Mars',
 'Harte': 'Mars',
 'Hartley': 'Earth',
 'Hartz': 'Earth',
 'Harverez': 'Earth',
 'Haste': 'Mars',
 'Haydenez': 'Earth',
 'Haydenzier': 'Earth',
 'Hayder': 'Earth',

In [143]:
train['HomePlanet'].fillna(train['familyname'].map(name_dict), inplace = True)

---

In [144]:
train.groupby(['Destination', 'HomePlanet']).size()

Destination    HomePlanet
55 Cancri e    Earth          700
               Europa         902
               Mars           196
PSO J318.5-22  Earth          725
               Europa          19
               Mars            51
TRAPPIST-1e    Earth         3177
               Europa        1214
               Mars          1515
dtype: int64

In [145]:
dest_dict = {'55 Cancri e' : 'Europa', 'PSO J318.5-22' : 'Earth', 'TRAPPIST-1e' : 'Earth'}

In [146]:
train['HomePlanet'].fillna(train['Destination'].map(dest_dict), inplace = True)

In [147]:
train['HomePlanet'].isnull().sum()

0

### VIP

In [148]:
train['VIP'].value_counts(dropna=False)

False    8291
NaN       203
True      199
Name: VIP, dtype: int64

In [149]:
train['VIP'].fillna(False, inplace = True)

### Fee

In [150]:
fee_list = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']

In [151]:
for col in fee_list:
    train[col].fillna(train[col].median(), inplace =True)

In [152]:
train['Fee'] = train['RoomService'] + train['FoodCourt'] + train['ShoppingMall'] + train['Spa'] + train['VRDeck']

### Cabin

In [153]:
train['deck'] = train['Cabin'].str.split('/').str[0]

In [154]:
train['side'] = train['Cabin'].str.split('/').str[-1]

In [155]:
train.groupby(['HomePlanet', 'deck']).size()

HomePlanet  deck
Earth       D          1
            E        404
            F       1652
            G       2559
Europa      A        256
            B        779
            C        747
            D        192
            E        133
            T          5
Mars        D        285
            E        339
            F       1142
dtype: int64

In [156]:
train['deck'].fillna(train['HomePlanet'].map({'Earth': 'G', 'Europa': 'B', 'Mars': 'F'}), inplace = True)

In [157]:
train['deck'].isnull().sum()

0

In [158]:
side_group = train.groupby(['Group', 'side']).size().reset_index()

In [159]:
side_group_dic = {}
for k, v in zip(side_group['Group'], side_group['side']):
    side_group_dic[k] = v

In [160]:
train['side'].fillna(train['Group'].map(side_group_dic), inplace =True)

In [161]:
train['side'].fillna('S',inplace = True)

### Destination

In [162]:
dest_group = train.groupby(['Group', 'Destination']).size().reset_index()

In [163]:
dest_group = dest_group.sort_values(0, ascending=False)

In [164]:
dest_group = dest_group.drop_duplicates() # 그룹에 따라 다른 행선지 향하는 애들 있었나?

In [165]:
dest_dict = {}
for g, d in zip(dest_group['Group'], dest_group['Destination']):
    dest_dict[g] = d

In [166]:
train['Destination'].fillna(train['Group'].map(dest_dict), inplace = True)

In [167]:
train['Destination'].fillna('TRAPPIST-1e', inplace = True)

### Cryosleep

In [168]:
train[train['Fee'] == 0.0]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Group,familyname,Fee,deck,side
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0001,Ofracculy,0.0,B,P
7,0006_02,Earth,True,G/0/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,0.0,Candra Jacostaffey,True,0006,Jacostaffey,0.0,G,S
9,0008_01,Europa,True,B/1/P,55 Cancri e,14.0,False,0.0,0.0,0.0,0.0,0.0,Erraiam Flatic,True,0008,Flatic,0.0,B,P
10,0008_02,Europa,True,B/1/P,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Altardr Flatic,True,0008,Flatic,0.0,B,P
18,0016_01,Mars,True,F/5/P,TRAPPIST-1e,45.0,False,0.0,0.0,0.0,0.0,0.0,Alus Upead,True,0016,Upead,0.0,F,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8680,9268_01,Earth,True,G/1505/P,TRAPPIST-1e,31.0,False,0.0,0.0,0.0,0.0,0.0,Agnesa Baldson,True,9268,Baldson,0.0,G,P
8681,9270_01,Earth,True,G/1497/S,55 Cancri e,33.0,False,0.0,0.0,0.0,0.0,0.0,Lan Mckinsond,True,9270,Mckinsond,0.0,G,S
8684,9274_01,Earth,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True,9274,Bullisey,0.0,G,P
8685,9275_01,Europa,False,A/97/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Polaton Conable,True,9275,Conable,0.0,A,P
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False,9278,Mondalley,0.0,G,S

In [169]:
train['CryoSleep'] = np.where(train['Fee'] > 0, False, True)

### Age

In [170]:
train['Age'].fillna(train['Age'].median(),inplace = True)

### 돌리기 전 정리

In [171]:
del_col = ['PassengerId', 'Cabin', 'Name', 'familyname']

In [172]:
train = train.drop(del_col, axis =1)

### 인코딩

In [173]:
from sklearn.preprocessing import LabelEncoder

In [174]:
label = LabelEncoder()

In [175]:
obj_col = []

for i, j in zip(train.dtypes.index, train.dtypes.values):
    if j == 'object':
        obj_col.append(i)

In [176]:
obj_col

['HomePlanet', 'Destination', 'Group', 'deck', 'side']

In [177]:
for col in obj_col:
    train[col] = label.fit_transform(train[col])

In [178]:
train

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Fee,deck,side
0,1,True,2,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,0.0,1,0
1,0,False,2,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,736.0,5,1
2,1,False,2,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,2,10383.0,0,1
3,1,False,2,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,2,5176.0,0,1
4,0,False,2,16.0,False,303.0,70.0,151.0,565.0,2.0,True,3,1091.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,1,False,0,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,6213,8536.0,0,0
8689,0,True,1,18.0,False,0.0,0.0,0.0,0.0,0.0,False,6214,0.0,6,1
8690,0,False,2,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,6215,1873.0,6,1
8691,1,False,0,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,6216,4637.0,4,1
8692,1,False,2,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,6216,4826.0,4,1

## test

### 전처리

In [179]:
# planet...

In [180]:
test['Group'] = test['PassengerId'].str[:4]
test['HomePlanet'].fillna(test['Group'].map(home_dict), inplace = True)

In [181]:
test['familyname'] = test['Name'].str.split(' ').str[-1]
test['HomePlanet'].fillna(test['familyname'].map(name_dict), inplace = True)

In [182]:
dest_dict = {'55 Cancri e' : 'Europa', 'PSO J318.5-22' : 'Earth', 'TRAPPIST-1e' : 'Earth'}

test['HomePlanet'].fillna(test['Destination'].map(dest_dict), inplace = True)

In [183]:
# vip

In [184]:
test['VIP'].fillna(False, inplace = True)

In [185]:
# fee

In [186]:
fee_list = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
for col in fee_list:
    test[col].fillna(test[col].median(), inplace =True)

In [187]:
test['Fee'] = test['RoomService'] + test['FoodCourt'] + test['ShoppingMall'] + test['Spa'] + test['VRDeck']

In [188]:
# cabin

In [189]:
test['deck'] = test['Cabin'].str.split('/').str[0]
test['side'] = test['Cabin'].str.split('/').str[-1]

In [190]:
test['deck'].fillna(test['HomePlanet'].map({'Earth': 'G', 'Europa': 'B', 'Mars': 'F'}), inplace = True)

In [191]:
side_group_dic = {}
for k, v in zip(side_group['Group'], side_group['side']):
    side_group_dic[k] = v

In [192]:
test['side'].fillna(test['Group'].map(side_group_dic), inplace =True)

In [193]:
test['side'].fillna('S', inplace = True)

In [194]:
# Destination

In [195]:
dest_group = train.groupby(['Group', 'Destination']).size().reset_index()
dest_group = dest_group.sort_values(0, ascending=False)
dest_group = dest_group.drop_duplicates()

dest_dict = {}
for g, d in zip(dest_group['Group'], dest_group['Destination']):
    dest_dict[g] = d

In [196]:
test['Destination'].fillna(test['Group'].map(dest_dict), inplace = True)

In [197]:
test['Destination'].fillna('TRAPPIST-1e', inplace = True)

In [198]:
# Cryo

In [199]:
test['CryoSleep'] = np.where(test['Fee'] > 0, False, True)

In [200]:
# Age

In [201]:
test['Age'].fillna(test['Age'].median(),inplace = True)

### 정리

In [202]:
del_col = ['PassengerId', 'Cabin', 'Name', 'familyname']

In [204]:
test = test.drop(del_col, axis =1)

### 인코딩

In [205]:
from sklearn.preprocessing import LabelEncoder

In [206]:
label = LabelEncoder()

In [207]:
obj_col = []

for i, j in zip(test.dtypes.index, test.dtypes.values):
    if j == 'object':
        obj_col.append(i)

In [208]:
for col in obj_col:
    test[col] = label.fit_transform(test[col])

## 모델...

In [209]:
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [210]:
x = train.drop('Transported', axis = 1)
y = train['Transported']

In [211]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

In [212]:
xgb = XGBClassifier()
rf = RandomForestClassifier()

In [213]:
xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [214]:
xgb.score(x_train, y_train)

0.9378774805867127

In [215]:
xgb.score(x_test, y_test)

0.8073605520414031

In [216]:
train

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Fee,deck,side
0,1,True,2,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,0.0,1,0
1,0,False,2,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,736.0,5,1
2,1,False,2,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,2,10383.0,0,1
3,1,False,2,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,2,5176.0,0,1
4,0,False,2,16.0,False,303.0,70.0,151.0,565.0,2.0,True,3,1091.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,1,False,0,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,6213,8536.0,0,0
8689,0,True,1,18.0,False,0.0,0.0,0.0,0.0,0.0,False,6214,0.0,6,1
8690,0,False,2,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,6215,1873.0,6,1
8691,1,False,0,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,6216,4637.0,4,1
8692,1,False,2,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,6216,4826.0,4,1

In [217]:
xgb.predict(test)

array([1, 0, 1, ..., 1, 1, 1])

In [218]:
sample_submission

     PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [219]:
sample_submission['Transported'] = xgb.predict(test)

In [220]:
sample_submission['Transported'] = np.where(sample_submission['Transported'] == 0, False, True)

In [222]:
sample_submission.to_csv('submission.csv', index = False)

In [113]:
train

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Fee,deck,side
0,1,True,2,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0,0.0,1,0
1,0,False,2,24.0,False,109.0,9.0,25.0,549.0,44.0,True,1,736.0,5,1
2,1,False,2,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,2,10383.0,0,1
3,1,False,2,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,2,5176.0,0,1
4,0,False,2,16.0,False,303.0,70.0,151.0,565.0,2.0,True,3,1091.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,1,False,0,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,6213,8536.0,0,0
8689,0,True,1,18.0,False,0.0,0.0,0.0,0.0,0.0,False,6214,0.0,6,1
8690,0,False,2,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,6215,1873.0,6,1
8691,1,False,0,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,6216,4637.0,4,1
8692,1,False,2,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,6216,4826.0,4,1