In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('elevator.csv', encoding = 'euc-kr')

In [4]:
df

,address1,address2,buldNm,elevatorNo,elvtrStts,lastInspctDe,liveLoad,manufacturerTelno
0,서울특별시 은평구 연서로 71,(역촌동),(재)살림이,81201,운행중,2022-05-24,550 KG,055-269-4114
1,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,42569,운행중,2022-10-11,1150 KG,055-289-8235
2,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,42570,운행중,2022-10-11,1150 KG,055-289-8235
3,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),104893,운행중,2022-11-03,1150 KG,043-722-1000
4,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),4213,운행중,2022-11-03,2000 KG,032-815-7871
...,...,...,...,...,...,...,...,...
195,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,155005,운행중,2022-07-11,1000 KG,043-722-1000
196,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,154984,운행중,2022-06-15,1000 KG,043-722-1000
197,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,154985,운행중,2022-06-15,1000 KG,043-722-1000
198,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,155230,운행중,2022-10-31,1000 KG,043-722-1000
199,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,155231,운행중,2022-10-31,1000 KG,043-722-1000

In [5]:
df['elevatorNo'] = df['elevatorNo'].astype(str)

In [6]:
for i in df['elevatorNo']:
    df = df.replace(i, i.zfill(7))

In [7]:
df

,address1,address2,buldNm,elevatorNo,elvtrStts,lastInspctDe,liveLoad,manufacturerTelno
0,서울특별시 은평구 연서로 71,(역촌동),(재)살림이,0081201,운행중,2022-05-24,550 KG,055-269-4114
1,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042569,운행중,2022-10-11,1150 KG,055-289-8235
2,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042570,운행중,2022-10-11,1150 KG,055-289-8235
3,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0104893,운행중,2022-11-03,1150 KG,043-722-1000
4,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0004213,운행중,2022-11-03,2000 KG,032-815-7871
...,...,...,...,...,...,...,...,...
195,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155005,운행중,2022-07-11,1000 KG,043-722-1000
196,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154984,운행중,2022-06-15,1000 KG,043-722-1000
197,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154985,운행중,2022-06-15,1000 KG,043-722-1000
198,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155230,운행중,2022-10-31,1000 KG,043-722-1000
199,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155231,운행중,2022-10-31,1000 KG,043-722-1000

In [ ]:
col_list = ['lastInspctDe', 'inspctInstt' ,'lastResultNm']
data1 = []

for num in df['elevatorNo']:
    url = 'https://apis.data.go.kr/openapi/service/ElevatorInformationService/getElevatorView'
    serviceKey = 'gCLmjgZMbPHHz6PrGczbNvDfSRCuK6tNGdbBdtpZYGexF1SiOZ92Lp2wZRhF23AEKfy3WrSvJ/LOc6chgTaMhw=='
    elevator_no = num

    params = {'serviceKey' : serviceKey, 'elevator_no' : elevator_no}
    req = requests.get(url, params = params, verify = False)
    soup = BeautifulSoup(req.text, 'lxml')

In [24]:
data3 = []

for num in tqdm(df['elevatorNo']):
    url = 'https://apis.data.go.kr/openapi/service/ElevatorInformationService/getElevatorView'
    serviceKey = 'gCLmjgZMbPHHz6PrGczbNvDfSRCuK6tNGdbBdtpZYGexF1SiOZ92Lp2wZRhF23AEKfy3WrSvJ/LOc6chgTaMhw=='
    elevator_no = num

    params = {'serviceKey' : serviceKey, 'elevator_no' : elevator_no}
    req = requests.get(url, params = params, verify = False)
    soup = BeautifulSoup(req.text, 'xml')
    
    
    temp = []
    
    temp.append(num)
    try:
        temp.append(soup.item.select('lastInspctDe')[0].text)
    except:
        temp.append('')
    try: 
        temp.append(soup.item.select('inspctInstt')[0].text)
    except:
        temp.append('')
    try:
        temp.append(soup.item.select('lastResultNm')[0].text)
    except:
        temp.append('')
    
    data3.append(temp)

100%|██████████| 200/200 [07:44<00:00,  2.32s/it]

In [22]:
data3

[['0081201', '2022-05-24', '한국승강기안전공단 서울서부지사', '합격'],
 ['0042569', '2022-10-11', '한국승강기안전공단 서울서부지사', '합격']]

In [38]:
col_list = ['elevatorNo', 'lastInspctDe', 'inspctInstt' ,'lastResultNm']

In [39]:
soup.item.select('lastInspctDe')[0].text

'2022-10-31'

In [42]:
df1 = pd.DataFrame(data3, columns = col_list)
df1

    elevatorNo lastInspctDe       inspctInstt lastResultNm
0      0081201   2022-05-24  한국승강기안전공단 서울서부지사           합격
1      0042569   2022-10-11  한국승강기안전공단 서울서부지사           합격
2      0042570   2022-10-11  한국승강기안전공단 서울서부지사        조건부합격
3      0104893   2022-11-03  한국승강기안전공단 서울서부지사        조건부합격
4      0004213   2022-11-03  한국승강기안전공단 서울서부지사        조건부합격
..         ...          ...               ...          ...
195    0155005   2022-07-11  한국승강기안전공단 서울서부지사        보완후합격
196    0154984   2022-06-15  한국승강기안전공단 서울서부지사        보완후합격
197    0154985   2022-06-15  한국승강기안전공단 서울서부지사        보완후합격
198    0155230   2022-10-31  한국승강기안전공단 서울서부지사        보완후합격
199    0155231   2022-10-31  한국승강기안전공단 서울서부지사        보완후합격

[200 rows x 4 columns]

In [41]:
df

,address1,address2,buldNm,elevatorNo,elvtrStts,lastInspctDe,liveLoad,manufacturerTelno
0,서울특별시 은평구 연서로 71,(역촌동),(재)살림이,0081201,운행중,2022-05-24,550 KG,055-269-4114
1,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042569,운행중,2022-10-11,1150 KG,055-289-8235
2,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042570,운행중,2022-10-11,1150 KG,055-289-8235
3,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0104893,운행중,2022-11-03,1150 KG,043-722-1000
4,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0004213,운행중,2022-11-03,2000 KG,032-815-7871
...,...,...,...,...,...,...,...,...
195,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155005,운행중,2022-07-11,1000 KG,043-722-1000
196,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154984,운행중,2022-06-15,1000 KG,043-722-1000
197,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154985,운행중,2022-06-15,1000 KG,043-722-1000
198,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155230,운행중,2022-10-31,1000 KG,043-722-1000
199,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155231,운행중,2022-10-31,1000 KG,043-722-1000

In [44]:
df_total = pd.merge(df, df1, on= 'elevatorNo')

In [45]:
df_total

,address1,address2,buldNm,elevatorNo,elvtrStts,lastInspctDe_x,liveLoad,manufacturerTelno,lastInspctDe_y,inspctInstt,lastResultNm
0,서울특별시 은평구 연서로 71,(역촌동),(재)살림이,0081201,운행중,2022-05-24,550 KG,055-269-4114,2022-05-24,한국승강기안전공단 서울서부지사,합격
1,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042569,운행중,2022-10-11,1150 KG,055-289-8235,2022-10-11,한국승강기안전공단 서울서부지사,합격
2,서울특별시 은평구 통일로71길 16,(대조동),(주)KT 은평지사,0042570,운행중,2022-10-11,1150 KG,055-289-8235,2022-10-11,한국승강기안전공단 서울서부지사,조건부합격
3,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0104893,운행중,2022-11-03,1150 KG,043-722-1000,2022-11-03,한국승강기안전공단 서울서부지사,조건부합격
4,서울특별시 은평구 은평로13길 12-1,해명빌딩 (녹번동),(주)녹번해명(해명빌딩),0004213,운행중,2022-11-03,2000 KG,032-815-7871,2022-11-03,한국승강기안전공단 서울서부지사,조건부합격
...,...,...,...,...,...,...,...,...,...,...,...
195,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155005,운행중,2022-07-11,1000 KG,043-722-1000,2022-07-11,한국승강기안전공단 서울서부지사,보완후합격
196,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154984,운행중,2022-06-15,1000 KG,043-722-1000,2022-06-15,한국승강기안전공단 서울서부지사,보완후합격
197,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0154985,운행중,2022-06-15,1000 KG,043-722-1000,2022-06-15,한국승강기안전공단 서울서부지사,보완후합격
198,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155230,운행중,2022-10-31,1000 KG,043-722-1000,2022-10-31,한국승강기안전공단 서울서부지사,보완후합격
199,서울특별시 은평구 수색동 115-5,(수색동),DMC파인시티,0155231,운행중,2022-10-31,1000 KG,043-722-1000,2022-10-31,한국승강기안전공단 서울서부지사,보완후합격