In [32]:
import pandas as pd
import numpy as np

In [33]:
midwest = pd.read_csv('midwest.csv')

In [34]:
df = pd.DataFrame(midwest)

In [35]:
df

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,35.396784,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,16.549869,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,15.064584,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,24.995504,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,21.666382,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR

In [40]:
df = df.rename({'poptotal' : 'total', 'popasian': 'asian'}, axis = 1)

In [ ]:
df.rename({}, axis=1, inplace = True)
df.rename(columns = {})

In [41]:
df

,PID,county,state,area,total,popdensity,popwhite,popblack,popamerindian,asian,...,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,35.396784,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,16.549869,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,15.064584,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,24.995504,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,21.666382,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR

In [42]:
df['pertotalasian'] = df['asian'] / df['total'] * 100

In [43]:
df

,PID,county,state,area,total,popdensity,popwhite,popblack,popamerindian,asian,...,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,pertotalasian
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,0.376759
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,0.451722
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,0.106731
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,0.486918
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,0.085675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,0.885746
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,0.199549
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,0.221821
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,1.231471
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,0.980912

In [44]:
df['pertotalasian'].mean()

0.48724618343573406

In [46]:
def asianMean(c): #변수가 밖에 있다! 위험하게 작성한 예시임....
    if c > (df['pertotalasian'].mean()):
        return 'large'
    return 'small'

In [52]:
def isSize(percent, mean):
    if percent > mean:
        return 'large'
    return 'small'

In [47]:
df['asianMean']= df['pertotalasian'].apply(asianMean)

In [48]:
df['asianMean'].value_counts()

small    318
large    119
Name: asianMean, dtype: int64

In [49]:
df

,PID,county,state,area,total,popdensity,popwhite,popblack,popamerindian,asian,...,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,pertotalasian,asianMean
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,0.376759,small
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,0.451722,small
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,0.106731,small
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,0.486918,small
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,0.085675,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,0.885746,large
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,0.199549,small
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,0.221821,small
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,1.231471,large
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,0.980912,large

In [50]:
df['asianMean2']= np.where(df['pertotalasian'] > (df['pertotalasian'].mean()), 'large', 'small')

In [51]:
df['asianMean2'].value_counts()

small    318
large    119
Name: asianMean2, dtype: int64

---------------------

In [56]:
midwest = pd.read_csv('midwest.csv')
df = pd.DataFrame(midwest)

In [57]:
df

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,35.396784,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,16.549869,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,15.064584,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,24.995504,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,21.666382,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR

In [84]:
df['percent'] = (df['poptotal'] - df['popadults']) / df['poptotal'] *100

In [85]:
df['percent']

0      34.486307
1      36.721250
2      35.501301
3      37.440758
4      31.819740
         ...
432    35.731093
433    34.693302
434    31.307712
435    36.602052
436    36.422797
Name: percent, Length: 437, dtype: float64

In [90]:
df.sort_values('percent', ascending = False)[['county', 'percent']][:5]

        county    percent
230   ISABELLA  51.501172
404  MENOMINEE  50.591260
281     ATHENS  49.320727
247    MECOSTA  49.059183
154     MONROE  47.358182

In [86]:
(df['percent'].sort_values()).tail(5)

154    47.358182
247    49.059183
281    49.320727
404    50.591260
230    51.501172
Name: percent, dtype: float64

In [87]:
df['perGrade'] = np.where(df['percent'] >= 40, 'large',
np.where(df['percent'] >= 30, 'middle', 'small'))

In [88]:
df

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,percent,perGrade
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307,middle
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250,middle
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301,middle
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758,middle
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,35.731093,middle
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,34.693302,middle
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,31.307712,middle
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,36.602052,middle
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,36.422797,middle

In [89]:
df['perGrade'].value_counts()

middle    396
large      32
small       9
Name: perGrade, dtype: int64

In [93]:
df

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,percent,perGrade,asian_per
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307,middle,0.376759
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250,middle,0.451722
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301,middle,0.106731
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758,middle,0.486918
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740,middle,0.085675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,35.731093,middle,0.885746
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,34.693302,middle,0.199549
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,31.307712,middle,0.221821
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,36.602052,middle,1.231471
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,36.422797,middle,0.980912

In [98]:
df = df.rename({'poptotal' : 'total' , 'popasian' : 'asian'}, axis = 1)

In [99]:
df

,PID,county,state,area,total,popdensity,popwhite,popblack,popamerindian,asian,...,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,percent,perGrade,asian_per
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307,middle,0.376759
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250,middle,0.451722
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301,middle,0.106731
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758,middle,0.486918
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740,middle,0.085675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,35.731093,middle,0.885746
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,34.693302,middle,0.199549
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,31.307712,middle,0.221821
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,36.602052,middle,1.231471
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,36.422797,middle,0.980912

In [100]:
df['asian_per'] = df['asian'] / df['total'] *100

In [ ]:
df.sort_values('percent', ascending = False)[['county', 'percent']][:5]

In [104]:
df.groupby('state')['asian_per'].mean()

state
IL    0.563895
IN    0.382658
MI    0.506877
OH    0.432803
WI    0.556213
Name: asian_per, dtype: float64

In [105]:
df.groupby('state')['asian_per'].mean().sort_values()

state
IN    0.382658
OH    0.432803
MI    0.506877
WI    0.556213
IL    0.563895
Name: asian_per, dtype: float64

In [106]:
df['inmetro'].value_counts()

0    287
1    150
Name: inmetro, dtype: int64

In [107]:
df.loc[0, 'county'] = 'hello'

In [108]:
df

,PID,county,state,area,total,popdensity,popwhite,popblack,popamerindian,asian,...,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,percent,perGrade,asian_per
0,561,hello,IL,0.052,66090,1270.961540,63917,1702,98,249,...,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307,middle,0.376759
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250,middle,0.451722
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301,middle,0.106731
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758,middle,0.486918
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740,middle,0.085675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,35.731093,middle,0.885746
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,34.693302,middle,0.199549
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,31.307712,middle,0.221821
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,36.602052,middle,1.231471
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,36.422797,middle,0.980912